imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi: ~
    translator: { fallback: "%locale%" }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection:
        enabled: false
    validation:
        api: 2.4
        enable_annotations: false
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale: "%locale%"
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true
# Twig Configuration
twig:
    debug:                  "%kernel.debug%"
    strict_variables:       "%kernel.debug%"
    exception_controller:   'FOS\RestBundle\Controller\ExceptionController::showAction'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:     "%database_driver%"
                host:       "%database_host%"
                port:       "%database_port%"
                dbname:     "%database_name%"
                user:       "%database_user%"
                password:   "%database_password%"
                charset:    UTF8
                options:
                    1002:  "SET NAMES 'UTF8'"
                mapping_types:
                    enum: string
#                logging: false
#                profiling: false

    orm:
        default_entity_manager:         default
        auto_generate_proxy_classes:    "%kernel.debug%"

        entity_managers:
            default:
                connection:         default
                naming_strategy:    doctrine.orm.naming_strategy.underscore
#                metadata_cache_driver: redis
#                query_cache_driver: redis
#                result_cache_driver: redis
                mappings:
#                    # bundles
#
#                    TagcadeUserBundle:  ~
#                    TagcadeAdminApiBundle:  ~
#                    TagcadeUserSystemAdminBundle:  ~
#                    TagcadeUserSystemPublisherBundle:  ~
#                    TagcadeUserSystemSubPublisherBundle:  ~
#                    # custom
#                    CoreEntities:
#                        type:       yml
#                        dir:        %kernel.root_dir%/../src/Tagcade/Resources/config/doctrine/Core
#                        prefix:     Tagcade\Entity\Core
#                        alias:      TagcadeCoreEntity
#                        is_bundle:  false
#                    ReportEntities:
#                        type:       yml
#                        dir:        %kernel.root_dir%/../src/Tagcade/Resources/config/doctrine/Report
#                        prefix:     Tagcade\Entity\Report
#                        alias:      TagcadeReportEntity
#                        is_bundle:  false
#                    UnifiedReportPartnerEntities:
#                        type:       yml
#                        dir:        %kernel.root_dir%/../src/Tagcade/Resources/config/doctrine/PartnerReport
#                        prefix:     Tagcade\Entity\Report\PartnerReport
#                        alias:      TagcadePartnerReportEntity
#                        is_bundle:  false

#fos_user:
#    db_driver:      orm
#    firewall_name:  api
#    user_class:     Tagcade\Bundle\UserBundle\Entity\User


######################################################

# User system configuration

######################################################


lexik_jwt_authentication:
    private_key_path:   '%jwt_private_key_path%'
    public_key_path:    '%jwt_public_key_path%'
    pass_phrase:        '%jwt_key_pass_phrase%'
    token_ttl:          %jwt_token_ttl%


parameters:
    jms_serializer.json_serialization_visitor.class: Tagcade\Behaviors\JsonSerializationVisitor